# Generated by Django 3.2.14 on 2022-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
