# Generated by Django 3.2.14 on 2022-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogs_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="designation",
            field=models.CharField(default="nothing", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogs",
            name="Title",
            field=models.TextField(),
        ),
    ]
