# Generated by Django 3.2.14 on 2023-02-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_auto_20230202_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="anonymous_user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="comments",
            name="person_email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
