# Generated by Django 3.2.14 on 2022-09-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_queries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_messages",
            name="Description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="user_messages",
            name="Subject",
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name="user_messages",
            name="email",
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="user_messages",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
