# Generated by Django 3.2.14 on 2022-07-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0003_alter_plants_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plants",
            name="image",
            field=models.ImageField(upload_to="images/plants"),
        ),
    ]
