# Generated by Django 3.2.14 on 2022-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("designation", models.TextField()),
                ("testimonial", models.TextField()),
                ("display_picture", models.ImageField(upload_to="")),
            ],
        ),
    ]
