# Generated by Django 3.2.14 on 2022-07-20 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonials",
            name="designation",
        ),
    ]
