# Generated by Django 3.2.14 on 2023-02-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testimonials", "0003_alter_testimonials_display_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonials",
            name="display_picture",
            field=models.ImageField(upload_to="images/testimonials"),
        ),
    ]
